# Generated by Django 5.2.6 on 2025-10-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jobmodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmodel',
            name='status',
        ),
        migrations.AddField(
            model_name='applymodel',
            name='status',
            field=models.CharField(choices=[('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected')], max_length=100, null=True),
        ),
    ]
