# Generated by Django 5.2.6 on 2025-10-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_remove_jobmodel_status_applymodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applymodel',
            name='cv',
            field=models.FileField(null=True, upload_to='job/cv'),
        ),
    ]
